import Link from "next/link";
import NavBar from "@/components/NavBar";

import "./globals.css";
import { Inter } from "next/font/google";
import Reserves from "@/components/ReservesComponent";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "обменник валют",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        {/* <Reserves /> */}
        {children}
        </body>
    </html>
  );
}
